Repository cloudbees/arcalos-boot-config, pull requests merged in 2019-10, with the labels that each got.

#44 feat: can configure gitPublic as part of requirements
  .secrets.baseline
  env/jxboot-resources/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#45 chore: rename secret to replicate now that we dont use a fixed cluste…
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#46 fix: using hasKey around gitPublic
  env/jxboot-resources/values.tmpl.yaml
Labels: approved, size/XS

#47 feat: remove version override for jxboot-resources
  env/requirements.yaml
Labels: approved, size/XS

#48 chore: display the jx-requirements.yml after the override has happened
  jenkins-x.yml
Labels: size/XS

#49 feat: removing unused configuration
  bdd/bdd.sh
  bdd/boot-local/README.md
  bdd/boot-local/cluster.yaml
  bdd/boot-local/jx-requirements.yml
  bdd/boot-vault/README.md
  bdd/boot-vault/cluster.yaml
  bdd/boot-vault/jx-requirements.yml
  jenkins-x-bdd-local.yml
  jenkins-x-bdd-vault.yml
  jenkins-x-release.yml
  updatebot.sh
Labels: approved, size/L

#50 fix: added env vars for GIT users
  jenkins-x-release.yml
Labels: approved, size/XS

#51 feat: verify kuberhealthy state at end of release pipeline
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#53 feat: lets add install statuses to a custom resource so we can tell …
  env/install/finished/install-finished.yaml
  env/install/start/install-cdr.yaml
  env/install/start/install-started.yaml
  jenkins-x.yml
Labels: approved, size/M

#56 fix: updatebot PR onto version stream repo
  systems/acme/templates/cert-manager-prod-certificate.yaml
  systems/acme/templates/cert-manager-staging-certificate.yaml
  updatebot.sh
Labels: approved, size/XS

#57 fix: apply install crd in separate step
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#58 fix: add the jxt CLI commands
  jenkins-x.yml
Labels: size/S

#43 chore: added basic ci config for boot-config repo
  ci.sh
  jenkins-x-arcalos.yml
Labels: approved, size/L

#60 fix: use a different suffix 'abc' for boot config PRs
  jenkins-x-arcalos.yml
Labels: approved, size/XS

#59 fix: add annotations to jenkins-x-controllerbuild SA
  env/jenkins-x-platform/values.tmpl.yaml
Labels: size/XS

#62 chore: use the kaniko sa to write logs to GCS
  env/jenkins-x-platform/values.tmpl.yaml
Labels: size/XS
