Repository cloudbees/arcalos-boot-config, pull requests merged in 2019-12, with the labels that each got.

#151 fix: automated enablement of dns has stopped working, lets always ena…
  jx-requirements.yml
Labels: approved, lgtm, size/XS

#93 chore: add arcalos-role-controller
  env/requirements.yaml
Labels: approved, lgtm, size/XS

#173 fix: lets use a yaml string rather than bool
  env/templates/000-namespace.yaml
Labels: approved, lgtm, size/XS

#175 chore: configure velero plugins
  systems/velero/values.tmpl.yaml
Labels: approved, lgtm, size/S

#178 fix: disable volume snapshot backups
  systems/velero/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#180 velero config
  systems/velero-backups/templates/default-backup.yaml
  systems/velero-backups/values.tmpl.yaml
Labels: approved, size/XS

#182 feat: enable velero backups
  jx-requirements.yml
Labels: approved, lgtm, size/XS

#183 Revert "velero config"
  systems/velero-backups/templates/default-backup.yaml
  systems/velero-backups/values.tmpl.yaml
Labels: approved, lgtm, size/XS
