Repository cloudbees/arcalos-boot-config, pull requests merged in 2019-11, with the labels that each got.

#64 chore: create the user as an owner on boot
  adduser.sh
  jenkins-x.yml
Labels: size/S

#70 remove jx ui from each tenant and enable refresh token job when using github apps
  env/jx-app-sso/values.tmpl.yaml
  env/lighthouse/values.tmpl.yaml
  env/refresh/values.tmpl.yaml
  env/requirements.yaml
  env/sso-operator/values.tmpl.yaml
  env/templates/700-dashboard-ing.yaml
  env/templates/700-dex-ing.yaml
  env/values.tmpl.yaml
  jx-requirements.yml
Labels: approved, size/L

#77 fix: lets enable github app mode for tide if using github app
  env/lighthouse/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#75 fix: attempt to use a PR of arcalos
  ci.sh
  jenkins-x.yml
Labels: size/S

#74 chore: corrected format of jenkins-x.yml to reduce merge conflicts
  jenkins-x.yml
Labels: approved, size/L

#79 chore: use the storage account rather than jx-boot for build controller
  ci.sh
  env/jenkins-x-platform/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#82 fix: fixes for GitHub App support
  env/jxboot-resources/values.tmpl.yaml
  env/tekton/values.tmpl.yaml
Labels: approved, lgtm, size/S

#80 feat: added workload identity annotations to the tekton-bot serviceaccount
  env/values.tmpl.yaml
Labels: approved, lgtm, size/S

#86 fix: fix regresssion in build controller due to yaml replacement
  env/jenkins-x-platform/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#78 feat: add github app url
  jx-requirements.yml
Labels: approved, lgtm, size/XS

#52 chore: Upgrade cj image can be upgraded
  env/templates/upgrade-cj.yaml
  env/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#98 fix: use project name not number
  env/jenkins-x-platform/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#95 chore: get refresh tenant version from version stream
  env/refresh/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#106 fix: lets move the verify env after jxt commands
  env/repositorycontroller/values.tmpl.yaml
  env/requirements.yaml
  jenkins-x.yml
Labels: approved, lgtm, size/S

#99 chore: add segment
  env/jx-segment-controller/values.tmpl.yaml
  env/parameters.schema.json
  env/requirements.yaml
  jenkins-x-arcalos.yml
Labels: approved, lgtm, size/S

#113 chore: move get token after vault install
  jenkins-x.yml
Labels: approved, lgtm, size/S

#118 fix: repository controller
  env/repositorycontroller/values.tmpl.yaml
  env/requirements.yaml
Labels: approved, lgtm, size/S

#120 feat: add velero backup config
  jenkins-x.yml
  systems/velero-backups/Chart.yaml
  systems/velero-backups/README.MD
  systems/velero-backups/templates/default-backup.yaml
  systems/velero-backups/values.tmpl.yaml
  systems/velero/Chart.yaml
  systems/velero/README.MD
  systems/velero/requirements.yaml
  systems/velero/values.tmpl.yaml
Labels: approved, lgtm, size/L

#122 feat: corrected secret name for replication
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#121 chore: move the vault installation to the start of the boot process
  jenkins-x.yml
  systems/vault/vault-ing.tmpl.yaml
Labels: approved, lgtm, size/M

#135 chore: disable the docker socket
  .secrets.baseline
  env/jenkins-x-platform/values.tmpl.yaml
  env/values.tmpl.yaml
Labels: approved, lgtm, size/S

#101 fix: refactored tekton-bot serviceaccount annotations config
  env/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#136 fix: lets run the refresh job every 15 mins
  env/refresh/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#139 fix: use the version stream for the repo ctrl
  env/requirements.yaml
Labels: approved, lgtm, size/XS

#141 Revert "fix: use the version stream for the repo ctrl"
  env/requirements.yaml
Labels: size/XS

#142 Revert "Revert "fix: use the version stream for the repo ctrl""
  env/requirements.yaml
Labels: size/XS

#143 chore: upgrade to latest release of version stream
  env/templates/upgrade-cj.yaml
Labels: approved, lgtm, size/XS

#146 chore: avoid expose and cleanup jobs running by switching the refresh…
  env/requirements.yaml
Labels: approved, lgtm, size/XS
