Repository cloudbees/arcalos-boot-config, pull requests merged in 2020-05, with the labels that each got.

#383 chore: remove ingress config
  jenkins-x-arcalos.yml
Labels: size/XS

#390 chore: cleanup OWNERS
  OWNERS
Labels: approved, lgtm, size/S

#348 chore: disable chartmuseum
  .secrets.baseline
  env/jenkins-x-platform/values.tmpl.yaml
  env/jxboot-resources/values.tmpl.yaml
  env/values.tmpl.yaml
Labels: approved, size/M

#397 chore: ensure a string is passed to hashPassword
  env/jenkins-x-platform/values.tmpl.yaml
Labels: size/XS
