Repository cloudbees/arcalos-boot-config, pull requests merged in 2020-01, with the labels that each got.

#91 chore: cleanup
  env/parameters.schema.json
  jenkins-x-arcalos.yml
Labels: approved, lgtm, size/S

#197 chore: remove verbose flag from subcommands
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#200 chore: do not overrride gcactivities pod version
  env/jenkins-x-platform/values.tmpl.yaml
Labels: size/XS

#201 feat: configurable schedule and ttl for velero backups
  systems/velero-backups/templates/default-backup.yaml
  systems/velero-backups/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#199 feat: enable meta pipeline
  env/prow/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#202 chore: remove debug logging
  jenkins-x.yml
Labels: size/XS

#203 chore: use patched versions of tekton images
  .secrets.baseline
  env/tekton/values.tmpl.yaml
Labels: approved, lgtm, size/S

#204 chore: create jx-auth-config configmap
  env/lighthouse/values.tmpl.yaml
  jenkins-x.yml
  systems/jx-auth/Chart.yaml
  systems/jx-auth/jx-auth-configmap.tmpl.yaml
  systems/jx-auth/templates/jx-auth-configmap.yaml
Labels: approved, lgtm, size/M

#205 chore: set the Chart.yaml version to v1
  env/Chart.yaml
  repositories/Chart.yaml
  systems/acme/Chart.yaml
  systems/cm/Chart.yaml
  systems/external-dns/Chart.yaml
  systems/jxing/Chart.yaml
  systems/vault/Chart.yaml
Labels: approved, lgtm, size/XS
