Repository cloudbees/arcalos-boot-config, pull requests merged in 2020-02, with the labels that each got.

#206 chore: bring arcalos config inline with oss
  env/bucketrepo/values.tmpl.yaml
  env/jenkins-x-platform/values.tmpl.yaml
  env/nexus/values.tmpl.yaml
  env/nexus/values.yaml
  env/requirements.yaml
  env/sso-operator/values.tmpl.yaml
  jenkins-x-release.yml
  kubeProviders/aks/README.md
  kubeProviders/aks/values.tmpl.yaml
  kubeProviders/alibaba/README.md
  kubeProviders/alibaba/values.tmpl.yaml
  kubeProviders/aws/README.md
  kubeProviders/aws/values.tmpl.yaml
  kubeProviders/eks/README.md
  kubeProviders/eks/values.tmpl.yaml
  kubeProviders/icp/README.md
  kubeProviders/icp/values.tmpl.yaml
  kubeProviders/iks/README.md
  kubeProviders/iks/values.tmpl.yaml
  kubeProviders/kubernetes/README.md
  kubeProviders/kubernetes/values.tmpl.yaml
  kubeProviders/minikube/values.tmpl.yaml
  kubeProviders/minishift/values.tmpl.yaml
  kubeProviders/oke/README.md
  kubeProviders/oke/values.tmpl.yaml
  kubeProviders/openshift/values.tmpl.yaml
  kubeProviders/pks/README.md
  kubeProviders/pks/values.tmpl.yaml
Labels: approved, lgtm, size/XL

#211 fix: corrected yaml when bucketrepo is enabled
  env/bucketrepo/values.tmpl.yaml
  env/jenkins-x-platform/values.tmpl.yaml
Labels: approved, lgtm, size/S

#214 fix: disable chartmusuen ingress
  .secrets.baseline
  env/jxboot-resources/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#215 chore: make pipeline email & token optional
  env/parameters.schema.json
Labels: approved, lgtm, size/XS

#217 feat: only enable the jx-auth-config cm if github app is not used
  systems/jx-auth/jx-auth-configmap.tmpl.yaml
Labels: approved, lgtm, size/XS

#219 fix: remove unnecessary env vars
  ci.sh
  jenkins-x-arcalos.yml
Labels: size/S

#226 fix: prevent exposecontroller adding chartmuseum ingress
  .secrets.baseline
  env/jxboot-resources/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#227 chore: update variables for lighthouse
  jenkins-x-arcalos.yml
Labels: approved, size/M

#230 fix: missing pipeline vars
  ci.sh
  jenkins-x-arcalos.yml
Labels: approved, lgtm, size/S

#225 fix: toggle nexus using requirements repository configuration
  env/jxboot-resources/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#232 chore: unused pipeline vars
  jenkins-x-arcalos.yml
Labels: approved, lgtm, size/S
