Repository cloudbees/arcalos-boot-config, pull requests merged in 2020-04, with the labels that each got.

#296 chore: add step to verify dns
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#299 chore: enable stackdriver for gcpreviews
  env/jenkins-x-platform/values.tmpl.yaml
Labels: size/XS

#309 chore: log the refresh controller in stackdriver format
  env/refresh/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#316 fix: Update for Lighthouse changes
  env/lighthouse/values.tmpl.yaml
Labels: approved, lgtm, size/S

#319 chore: use patched version of gha image
  env/tekton/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#303 chore: use update workspace cmd
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#328 chore: add dashboard url as a configurable parameter
  env/parameters.schema.json
Labels: approved, lgtm, size/XS

#331 chore: default dashboard url to empty
  env/parameters.schema.json
Labels: size/XS

#334 chore: mount .dogrc
  jenkins-x-arcalos.yml
Labels: approved, lgtm, size/XS

#320 feat: enable lighthouse reporting
  env/lighthouse/values.tmpl.yaml
  env/parameters.schema.json
Labels: approved, lgtm, size/XS

#344 fix: update lighthouse url
  env/lighthouse/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#351 chore: remove the use of arcalos-secret
  jenkins-x-arcalos.yml
Labels: approved, lgtm, size/S
