Repository cloudbees/arcalos-boot-config, pull requests merged in 2020-03, with the labels that each got.

#239 chore: add missing prod sa to pipeline
  jenkins-x-arcalos.yml
Labels: approved, lgtm, size/S

#248 feat: now using the arcalos-alpha-prod-secret within the pipelines
  jenkins-x-arcalos.yml
Labels: approved, lgtm, size/XS

#247 fix: setting JX_LOG_FORMAT to stackdriver for the segment controller
  env/jx-segment-controller/values.tmpl.yaml
Labels: size/XS

#254 fix: temporary fix to allow users to view environment whilst performing quickstart
  adduser.sh
Labels: approved, lgtm, size/XS

#255 chore: use default_organisation rather than git_owner
  jenkins-x-arcalos.yml
Labels: size/XS

#257 fix: added environments view clusterrole for ui quickstarts
  .secrets.baseline
  adduser.sh
  env/templates/environments-view-clusterrole.yaml
  env/values.tmpl.yaml
Labels: approved, lgtm, size/S

#262 chore: enable verbose logging on repository controller
  env/repositorycontroller/values.tmpl.yaml
Labels: size/XS

#265 set JX_LOG_FORMAT to stackdriver
  env/controllerbuild/values.yaml
Labels: approved, lgtm, size/XS

#268 set JX_LOG_FORMAT to stackdriver
  env/controllerteam/values.yaml
Labels: approved, lgtm, size/XS

#270 chore: improved upgrade feature, allow PRs to merge
  env/templates/dev-scheduler.yaml
  env/templates/upgrade-cj.yaml
Labels: approved, lgtm, size/S

#266 fix: added ClusterRoleBinding to user
  adduser.sh
Labels: approved, lgtm, size/S

#271 chore: scale up lighthouse
  env/lighthouse/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#273 set JX_LOG_FORMAT to stackdriver
  env/controllerworkflow/values.yaml
  env/docker-registry/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#267 feat: update hmac as part of boot pipeline
  jenkins-x.yml
Labels: approved, size/XS

#278 feat: handle refactored lighthouse config
  env/lighthouse/values.tmpl.yaml
Labels: size/XS

#275 Remove env/jenkins values template as it's not used within APS
  env/jenkins/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#280 fix: remove update webhooks command
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#284 chore: remove trailing whitespace
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#285 fix: Scale up Lighthouse webhook controller to two pods
  env/lighthouse/values.tmpl.yaml
Labels: size/XS

#288 chore: remove plugins that don't exist in lighthouse
  env/templates/dev-scheduler.yaml
Labels: size/XS

#287 chore: enable stackdriver log format on build controller
  env/jenkins-x-platform/values.tmpl.yaml
Labels: size/XS

#289 chore: remove prow chart to reduce churn
  env/prow/README.MD
  env/prow/values.tmpl.yaml
  env/requirements.yaml
Labels: size/M

#286 chore: enable stackdriver logging for lighthouse
  env/lighthouse/values.tmpl.yaml
Labels: approved, lgtm, size/XS

#292 fix: improve dns ttl
  .secrets.baseline
  env/templates/700-kuberhealthy-ing.yaml
  env/values.tmpl.yaml
Labels: approved, lgtm, size/S

#293 chore: switch to stackdriver logging
  .secrets.baseline
  env/controllerbuild/values.yaml
  env/controllerteam/values.yaml
  env/controllerworkflow/values.yaml
  env/jenkins-x-platform/values.tmpl.yaml
Labels: size/S
